set cin nu rnu ts=4 sw=4 sts=4 et noswapfile nobackup
set so=100
set backspace=eol,start,indent
syntax on
set incsearch
set hlsearch
set ignorecase
set noexpandtab
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'gmarik/Vundle.vim'
    Plugin 'xjoi/codeforces.vim'
    Plugin 'vim-airline/vim-airline'
call vundle#end()
filetype plugin indent on
let g:airline#extensions#tabline#enabled = 1
set autochdir
nmap <tab> :bn <enter>
set cursorline
hi CursorLine   cterm=NONE ctermbg=238 ctermfg=none
:inoremap ( ()<ESC>i
:inoremap ) <c-r>=ClosePair(')')<CR>
:inoremap { {}<ESC>i<c-lf><ESC>k<s-$>a
:inoremap } <c-r>=ClosePair('}')<CR>
:inoremap [ []<ESC>i
:inoremap ] <c-r>=ClosePair(']')<CR>
:inoremap " ""<ESC>i
:inoremap ' ''<ESC>i
function! ClosePair(char)
	if getline('.')[col('.') - 1] == a:char
		return "\<Right>"
	else
		return a:char
	endif
endfunction
